location ~* ^/api/jobs/.*/events/ {
    include /etc/puppetlabs/nginx/conf.d/includes/orchestrator_cache_rules.inc;
}

location ~ ^/api/jobs/[0-9]+/nodes$ {
    include /etc/puppetlabs/nginx/conf.d/includes/orchestrator_cache_rules.inc;
}

location ~ ^/api/plan-jobs/[0-9]+/events/[0-9]+$ {
    include /etc/puppetlabs/nginx/conf.d/includes/orchestrator_cache_rules.inc;
}
